services:
  - type: web
    name: jewelleryauction
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run docker-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_products
